name: Compliance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fossa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: fossas/fossa-action@37f93d0aa19815e1bc2c9ff51125be5c0cd3f3b7 # main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
      - uses: fossas/fossa-action@37f93d0aa19815e1bc2c9ff51125be5c0cd3f3b7 # main
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
